Speedup to boards.py
mattheww/sgfmill pull request #2
Opened 2018-04-13 03:28 UTC by sethtroisi

I have a simple test script

```
from sgfmill import sgf
from sgfmill import sgf_moves
from sgfmill import ascii_boards

import os
import sys
import timeit

sgf_dir = sys.argv[1]
raw_sgf = []
for name in os.listdir(sgf_dir):
    print (name)
    if name.endswith('.sgf'):
        with open(os.path.join(sgf_dir, name)) as sgf_file:
            raw_sgf.append(sgf_file.read().encode('utf-8'))

print ("Loaded", len(raw_sgf))

def create():
    for data in raw_sgf:
        g = sgf.Sgf_game.from_bytes(data)
        board, moves = sgf_moves.get_setup_and_moves(g)
        for c, m in moves:
            if m != None:
                board.play(m[0], m[1], c)

    #print (ascii_boards.render_board(board))

print (timeit.timeit(create, number=1))
```

On 42 Professional games, 3.3s => 0.21s!
On 357 KGS games, 22.7 => 1.5!

This is like a 15x speedup for `play()`

2018-04-13 20:29 UTC, mattheww requested changes
Thanks, that looks like an easy improvement.

But I think it breaks ko detection, and I don't think it handles a single-stone self-capture correctly. Maybe adding `(r, c)` to the list of points would be enough to make it correct.

You can run the testsuite with `./run_sgfmill_testsuite`; that should help check.

2018-04-16 02:19 UTC, sethtroisi commented
Indeed I had forgot to include (r, c).

Old code failed two tests, with the minor change it now passes all tests.

I modified my script to output the final state and verified that over the 357 KGS games.

```
from sgfmill import sgf
from sgfmill import sgf_moves
from sgfmill import ascii_boards

import os
import sys
import timeit


sgf_dir = sys.argv[1]
raw_sgf = []
for name in sorted(os.listdir(sgf_dir)):
    if name.endswith('.sgf'):
        with open(os.path.join(sgf_dir, name)) as sgf_file:
            raw_sgf.append((name, sgf_file.read().encode('utf-8')))

print ("Loaded", len(raw_sgf))


def create():
    with open(sys.argv[2], "w") as log:
        for name, data in raw_sgf:
            g = sgf.Sgf_game.from_bytes(data)
            board, moves = sgf_moves.get_setup_and_moves(g)
            for c, m in moves:
                if m != None:
                    board.play(m[0], m[1], c)
            log.write("{},{}\n".format(name, ascii_boards.render_board(board)))


print (timeit.timeit(create, number=1))
```

2018-04-17 20:45 UTC, mattheww approved these changes

2018-04-17 20:46 UTC, mattheww commented
Thanks, I'll merge that and sort out a new release.

2018-04-17 21:07 UTC, sethtroisi commented
I might not cut a release right away, I have another 30% speedup in the works if you don't mind waiting a couple of days.

2018-04-17 21:08 UTC, mattheww commented
OK.

2018-04-25 07:55 UTC, sethtroisi commented
I made a pull request for the further improvement https://github.com/mattheww/sgfmill/pull/3, as I mentioned in that pull request I think this should go in regardless.

2018-05-15 15:55 UTC, sethtroisi commented
Friendly ping, it's been a month. Any chance you could take a look at this and merge #2 and potentially merge #3 ?

2018-05-20 15:19 UTC, merged